# Generated by Django 5.0.4 on 2024-05-01 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter name of employee', max_length=20)),
                ('second_name', models.CharField(help_text='Enter second name of employee', max_length=20)),
                ('role', models.CharField(choices=[('CA', 'Cashier'), ('OP', 'Operator'), ('AD', 'Administrator'), ('CO', 'Controller'), ('CL', 'Cleaner'), ('SE', 'Security'), ('SA', 'System Administrator')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a movie genre', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter hall', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('duration', models.IntegerField(help_text='Select duration in minutes')),
                ('budget', models.DecimalField(decimal_places=10, help_text='Select film budget', max_digits=19)),
                ('poster', models.ImageField(upload_to='posters/')),
                ('description', models.TextField(help_text='Enter a brief description of the film', max_length=1000)),
                ('rating', models.FloatField(help_text='Select rating for this film')),
                ('genre', models.ManyToManyField(help_text='Select a genre for this movie', to='cinema.genre')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(help_text='Enter date and time for session')),
                ('hall', models.ForeignKey(help_text='Enter hall for session', on_delete=django.db.models.deletion.CASCADE, to='cinema.hall')),
                ('movie', models.ForeignKey(help_text='Enter movie for session', on_delete=django.db.models.deletion.CASCADE, to='cinema.movie')),
            ],
        ),
        migrations.CreateModel(
            name='ShowSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(help_text='Enter start date/time for show schedule')),
                ('end_time', models.DateTimeField(help_text='Enter end date/time for show schedule')),
                ('hall', models.ForeignKey(help_text='Enter hall for show schedule', on_delete=django.db.models.deletion.CASCADE, to='cinema.hall')),
                ('movie', models.ForeignKey(help_text='Enter movie for show schedule', on_delete=django.db.models.deletion.CASCADE, to='cinema.movie')),
            ],
        ),
        migrations.CreateModel(
            name='TicketPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(help_text='Enter price')),
                ('session', models.OneToOneField(help_text='Enter session for ticket price', on_delete=django.db.models.deletion.CASCADE, to='cinema.session')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(help_text='Enter the employee who sold the ticket', on_delete=django.db.models.deletion.CASCADE, to='cinema.employee')),
                ('session', models.ForeignKey(help_text='Enter session for ticket', on_delete=django.db.models.deletion.CASCADE, to='cinema.session')),
                ('price', models.ForeignKey(help_text='Enter price for ticket', on_delete=django.db.models.deletion.CASCADE, to='cinema.ticketprice')),
            ],
        ),
    ]
