# Generated by Django 5.0.4 on 2024-05-01 19:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0004_alter_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this session', primary_key=True, serialize=False),
        ),
    ]
