# Generated by Django 5.0.4 on 2024-05-01 21:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0005_alter_session_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='showschedule',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='showschedule',
            name='hall',
        ),
        migrations.RemoveField(
            model_name='showschedule',
            name='start_time',
        ),
        migrations.AddField(
            model_name='showschedule',
            name='end_date_time',
            field=models.DateTimeField(default=datetime.datetime.now, help_text='Enter end date for show schedule'),
        ),
        migrations.AddField(
            model_name='showschedule',
            name='start_date_time',
            field=models.DateTimeField(default=datetime.datetime.now, help_text='Enter start date for show schedule'),
        ),
    ]
