# Generated by Django 5.0.4 on 2024-05-01 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0006_remove_showschedule_end_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='showschedule',
            old_name='end_date_time',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='showschedule',
            old_name='start_date_time',
            new_name='start_date',
        ),
    ]
