# Generated by Django 5.0.4 on 2024-05-09 17:24

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0007_rename_end_date_time_showschedule_end_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='image',
            field=models.ImageField(default='default.png', upload_to='images/avatars/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(default='+375291111111', max_length=13, validators=[django.core.validators.RegexValidator(message='Incorrect telephone number', regex='^\\+375(44|29)\\d{7}$')]),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(upload_to='images/posters/'),
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('email', models.EmailField(default='default@mail.ru', max_length=30)),
                ('birth_date', models.DateField(null=True, validators=[django.core.validators.MaxValueValidator(datetime.date(2006, 5, 14), message='You must be at least 18 years old to register')])),
                ('age', models.IntegerField(default=0)),
                ('phone_number', models.CharField(default='+375291111111', max_length=13, validators=[django.core.validators.RegexValidator(message='Incorrect telephone number', regex='^\\+375(44|29)\\d{7}$')])),
                ('image', models.ImageField(default='default.png', upload_to='images/avatars/')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
