# Generated by Django 5.0.4 on 2024-05-10 22:24

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0008_employee_image_employee_phone_number_employee_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='second_name',
        ),
        migrations.AddField(
            model_name='employee',
            name='surname',
            field=models.CharField(default='', help_text='Enter surname of employee', max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='birth_date',
            field=models.DateField(null=True, validators=[django.core.validators.MaxValueValidator(datetime.date(2006, 5, 16), message='You must be at least 18 years old to register')]),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(help_text='Enter name of client', max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='surname',
            field=models.CharField(help_text='Enter surname of client', max_length=20),
        ),
    ]
