# Generated by Django 5.0.4 on 2024-05-11 00:21

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0009_remove_employee_second_name_employee_surname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='birth_date',
            field=models.DateField(null=True, validators=[django.core.validators.MaxValueValidator(datetime.date(2006, 5, 16), message='You must be at least 18 years old to register')]),
        ),
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(default='default@mail.ru', max_length=30),
        ),
        migrations.AlterField(
            model_name='client',
            name='image',
            field=models.ImageField(default='avatars/default_client.png', upload_to='custom/avatars'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.ImageField(default='avatars/default_client.png', upload_to='custom/avatars'),
        ),
    ]
