# Generated by Django 5.0.4 on 2024-05-11 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0011_companyinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('description', models.CharField(default='', max_length=1000)),
                ('url', models.URLField(default='', max_length=1000)),
                ('image', models.ImageField(default='news/no_image_icon.png', upload_to='news/')),
                ('image_url', models.URLField(max_length=1000, null=True)),
            ],
        ),
    ]
