# Generated by Django 5.0.4 on 2024-05-11 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0013_alter_client_birth_date_alter_employee_birth_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='DictionaryOfTerms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=1000)),
                ('answer', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
