# Generated by Django 5.0.4 on 2024-05-12 16:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0015_vacancy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('rate', models.IntegerField(validators=[django.core.validators.MaxValueValidator(5, message='Your rate should be no more than 5'), django.core.validators.MinValueValidator(1, message='Your rate should be no less than 1')])),
                ('date', models.DateField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.client')),
            ],
        ),
    ]
