# Generated by Django 5.0.4 on 2024-05-12 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0016_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cinema.client'),
        ),
    ]
