# Generated by Django 5.0.4 on 2024-05-12 22:13

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0017_alter_review_sender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('discount', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(50, message="Discount shouldn't be more 50 %"), django.core.validators.MinValueValidator(2, message="Discount shouldn't be less than 2 %")])),
            ],
        ),
        migrations.AlterField(
            model_name='client',
            name='birth_date',
            field=models.DateField(null=True, validators=[django.core.validators.MaxValueValidator(datetime.date(2006, 5, 18), message='You must be at least 18 years old to register')]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='birth_date',
            field=models.DateField(null=True, validators=[django.core.validators.MaxValueValidator(datetime.date(2006, 5, 18), message='You must be at least 18 years old to register')]),
        ),
        migrations.CreateModel(
            name='UsedCoupons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.coupon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.client')),
            ],
        ),
    ]
