# Generated by Django 5.0.4 on 2024-05-12 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0018_coupon_alter_client_birth_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='promo',
            field=models.CharField(default='', max_length=20),
        ),
    ]
