# Generated by Django 5.0.4 on 2024-05-13 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0019_coupon_promo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='price',
            field=models.FloatField(help_text='Enter price'),
        ),
        migrations.CreateModel(
            name='TicketSelling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('promo_code', models.CharField(max_length=20, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='cinema.client')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.ticket')),
            ],
        ),
        migrations.DeleteModel(
            name='TicketPrice',
        ),
    ]
