# Generated by Django 5.0.4 on 2024-05-13 18:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0022_alter_movie_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime.now, help_text='Enter the date and time for the end of the session'),
        ),
        migrations.DeleteModel(
            name='ShowSchedule',
        ),
    ]
