# Generated by Django 5.0.4 on 2024-05-14 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0024_alter_client_birth_date_alter_employee_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(upload_to='images/posters'),
        ),
    ]
