# Generated by Django 5.0.4 on 2024-05-14 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0025_alter_movie_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(default='avatars/default_client.png', upload_to='images/posters'),
        ),
    ]
