# Generated by Django 5.0.4 on 2024-05-15 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0027_alter_client_birth_date_alter_employee_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
