# Generated by Django 5.0.4 on 2024-09-16 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0032_alter_client_birth_date_alter_employee_birth_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='articles/')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
