# Generated by Django 5.0.4 on 2024-09-16 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0033_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('logo', models.ImageField(upload_to='partners/')),
                ('link', models.URLField()),
            ],
        ),
    ]
