# Generated by Django 5.0.4 on 2024-09-17 21:43

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0035_alter_client_birth_date_alter_employee_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='count',
            field=models.IntegerField(default=1, help_text='Enter the number of tickets'),
        ),
        migrations.AlterField(
            model_name='client',
            name='birth_date',
            field=models.DateField(null=True, validators=[django.core.validators.MaxValueValidator(datetime.date(2006, 9, 23), message='You must be at least 18 years old to register')]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='birth_date',
            field=models.DateField(null=True, validators=[django.core.validators.MaxValueValidator(datetime.date(2006, 9, 23), message='You must be at least 18 years old to register')]),
        ),
    ]
