# Generated by Django 5.0.4 on 2024-09-17 21:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0036_ticket_count_alter_client_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='count',
            field=models.IntegerField(default=1, help_text='Enter the number of tickets', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
