# Generated by Django 5.0.4 on 2024-09-17 23:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0037_alter_ticket_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='count',
            new_name='amount',
        ),
        migrations.AddField(
            model_name='ticketselling',
            name='amount',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
