# Generated by Django 5.0.4 on 2024-09-18 15:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0038_rename_count_ticket_amount_ticketselling_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.ticket')),
            ],
        ),
    ]
