# Generated by Django 5.0.4 on 2024-09-18 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0040_cart_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cinema.ticket'),
        ),
    ]
