# Generated by Django 5.0.4 on 2024-09-18 21:31

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0043_alter_cart_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='birth_date',
            field=models.DateField(null=True, validators=[django.core.validators.MaxValueValidator(datetime.date(2006, 9, 24), message='You must be at least 18 years old to register')]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='birth_date',
            field=models.DateField(null=True, validators=[django.core.validators.MaxValueValidator(datetime.date(2006, 9, 24), message='You must be at least 18 years old to register')]),
        ),
    ]
