# Generated by Django 5.0.4 on 2024-09-19 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0044_alter_client_birth_date_alter_employee_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='summary',
            field=models.CharField(default='', max_length=85),
        ),
    ]
