# Generated by Django 5.0.4 on 2024-09-19 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0045_news_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictionaryofterms',
            name='summary',
            field=models.CharField(default='', max_length=40),
        ),
    ]
